import { useState, useRef } from "react";
import { 
  Shield, 
  QrCode, 
  LayoutDashboard, 
  AlertTriangle, 
  Plus, 
  ChevronRight, 
  Lock, 
  CheckCircle,
  Sparkles,
  Smartphone,
  Briefcase,
  BadgeCheck
} from "lucide-react";
import { motion, useInView } from "framer-motion";

function ManuSection() {
  const [isHovering, setIsHovering] = useState(false);
  const [activeFeature, setActiveFeature] = useState(0);
  const featuresRef = useRef(null);
  const isInView = useInView(featuresRef, { once: true });

  const AddProductButton = () => (
    <motion.button
      whileHover={{ scale: 1.05, y: -5 }}
      whileTap={{ scale: 0.95 }}
      className="flex items-center px-8 py-3 bg-gradient-to-r from-violet-600 to-indigo-600 text-white font-bold rounded-lg shadow-lg hover:shadow-violet-500/30 transition-all duration-300"
      onMouseEnter={() => setIsHovering(true)}
      onMouseLeave={() => setIsHovering(false)}
    >
      <Plus className="mr-2 w-5 h-5" />
      Add Product
      <ChevronRight className={`ml-2 w-5 h-5 transition-transform duration-300 ${isHovering ? 'translate-x-1' : ''}`} />
    </motion.button>
  );

  const features = [
    {
      icon: <Shield className="w-6 h-6 text-white" />,
      color: "from-violet-600 to-indigo-600",
      title: "Secure QR Codes",
      description: "Untraceable QR code generated by a blockchain system"
    },
    {
      icon: <QrCode className="w-6 h-6 text-white" />,
      color: "from-violet-500 to-purple-600",
      title: "User Friendly",
      description: "Easy scan for consumers and fast response"
    },
    {
      icon: <LayoutDashboard className="w-6 h-6 text-white" />,
      color: "from-indigo-600 to-violet-700",
      title: "Custom Dashboard",
      description: "Manufacturer dashboard to customize products"
    },
    {
      icon: <AlertTriangle className="w-6 h-6 text-white" />,
      color: "from-purple-600 to-indigo-700",
      title: "Fraud Alerts",
      description: "Get notified if you're scammed into buying counterfeit product"
    }
  ];

  // Manufacturer benefits
  const benefits = [
    {
      title: "Brand Protection",
      description: "Safeguard your brand from counterfeits",
      icon: <BadgeCheck className="w-5 h-5" />
    },
    {
      title: "Consumer Trust",
      description: "Build stronger customer confidence",
      icon: <Smartphone className="w-5 h-5" />
    },
    {
      title: "Market Analytics",
      description: "Gain insights from verification data",
      icon: <Briefcase className="w-5 h-5" />
    }
  ];

  // Animation variants
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1
      }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0 }
  };

  return (
    <section className="min-h-screen grid md:grid-cols-2" id="target-section">
      {/* Left side - Features */}
      <div className="bg-gradient-to-br from-indigo-950 via-violet-950 to-indigo-950 relative overflow-hidden flex flex-col justify-center px-8 md:px-12 py-16 md:py-0">
        {/* Background elements */}
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute -bottom-20 -left-20 w-80 h-80 bg-violet-500/10 rounded-full blur-3xl"></div>
          <div className="absolute top-1/4 right-0 w-64 h-64 bg-indigo-500/10 rounded-full blur-3xl"></div>
          <div className="absolute inset-0 hex-grid opacity-30"></div>
          
          {/* Animated background dots */}
          {[...Array(10)].map((_, i) => (
            <motion.div
              key={i}
              className="absolute w-2 h-2 bg-violet-500/20 rounded-full"
              initial={{ 
                x: Math.random() * 100 + '%', 
                y: Math.random() * 100 + '%',
                opacity: 0.2
              }}
              animate={{ 
                y: [
                  Math.random() * 100 + '%', 
                  Math.random() * 100 + '%'
                ],
                opacity: [0.2, 0.5, 0.2],
              }}
              transition={{ 
                duration: 10 + Math.random() * 20,
                repeat: Infinity,
                repeatType: "reverse"
              }}
            />
          ))}
        </div>
        
        <div className="max-w-lg mx-auto md:mx-0 md:ml-auto relative z-10">
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="inline-block mb-4"
          >
            <div className="flex items-center">
              <div className="bg-gradient-to-r from-violet-600 to-indigo-600 rounded-lg p-2 mr-3 shadow-lg shadow-violet-500/20">
                <Shield className="w-5 h-5 text-white" />
              </div>
              <span className="text-violet-400 font-bold">Manufacturer Solutions</span>
            </div>
          </motion.div>
          
          <motion.h1 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.1 }}
            viewport={{ once: true }}
            className="text-3xl sm:text-4xl md:text-5xl font-bold mb-8 tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-violet-400 via-purple-400 to-indigo-500"
          >
            What we offer with <span className="text-violet-400">BlockThief</span>
          </motion.h1>
          
          <motion.ul 
            ref={featuresRef}
            variants={containerVariants}
            initial="hidden"
            animate={isInView ? "visible" : "hidden"}
            className="text-gray-100 text-base md:text-lg space-y-6 mb-8"
          >
            {features.map((feature, index) => (
              <motion.li 
                key={index}
                variants={itemVariants}
                className="flex items-center transform transition-all duration-500"
                onMouseEnter={() => setActiveFeature(index)}
                whileHover={{ x: -10 }}
              >
                <motion.div 
                  className={`bg-gradient-to-r ${feature.color} p-3 rounded-lg mr-4 shadow-lg relative overflow-hidden`}
                  whileHover={{ scale: 1.1 }}
                  transition={{ type: "spring", stiffness: 400, damping: 10 }}
                >
                  {/* Sparkle effect on hover */}
                  {activeFeature === index && (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      exit={{ opacity: 0 }}
                      className="absolute -top-1 -right-1"
                    >
                      <Sparkles className="w-3 h-3 text-yellow-300" />
                    </motion.div>
                  )}
                  {feature.icon}
                </motion.div>
                <div className={`border-b ${activeFeature === index ? 'border-violet-500/70' : 'border-violet-500/20'} pb-2 flex-grow transition-all duration-300`}>
                  <h3 className="font-semibold text-white mb-1">{feature.title}</h3>
                  <p className="text-gray-300">{feature.description}</p>
                </div>
              </motion.li>
            ))}
          </motion.ul>
          
          {/* Security badge */}
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.6 }}
            viewport={{ once: true }}
            className="flex items-center mt-8"
          >
            <div className="flex items-center bg-indigo-950/70 backdrop-blur-sm rounded-full px-4 py-2 border border-violet-500/20 hover:border-violet-500/50 transition-all duration-300">
              <motion.div 
                animate={{ scale: [1, 1.2, 1] }}
                transition={{ duration: 2, repeat: Infinity }}
                className="bg-gradient-to-r from-violet-500 to-indigo-500 h-3 w-3 rounded-full mr-2"
              ></motion.div>
              <p className="text-violet-400 text-sm font-medium">Blockchain technology secured</p>
            </div>
          </motion.div>
        </div>
      </div>
      
      {/* Right side - Call to action */}
      <div className="w-full h-full bg-gradient-to-br from-indigo-950 via-violet-950 to-indigo-950 relative overflow-hidden flex items-center justify-center p-8 md:p-12">
        {/* Background elements */}
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute top-0 left-1/3 w-96 h-96 bg-indigo-500/10 rounded-full blur-3xl"></div>
          <div className="absolute bottom-1/4 right-0 w-64 h-64 bg-violet-500/10 rounded-full blur-3xl"></div>
          <div className="absolute inset-0 hex-grid opacity-30"></div>
          
          {/* Decorative blockchain elements */}
          <div className="absolute w-full h-full">
            {[0, 60, 120, 180, 240, 300].map((angle, i) => (
              <motion.div 
                key={i}
                initial={{ opacity: 0 }}
                animate={{ opacity: [0.3, 0.7, 0.3] }}
                transition={{ duration: 4 + i, repeat: Infinity, delay: i * 0.5 }}
                className="absolute top-1/2 left-1/2 w-1/3 h-0.5 bg-gradient-to-r from-transparent via-violet-500/20 to-transparent"
                style={{ transform: `translate(-50%, -50%) rotate(${angle}deg)` }}
              ></motion.div>
            ))}
          </div>
        </div>
        
        <motion.div 
          initial={{ opacity: 0, scale: 0.9 }}
          whileInView={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.6 }}
          viewport={{ once: true }}
          className="max-w-lg relative z-10"
        >
          {/* Glowing title */}
          <div className="relative mb-8">
            <div className="absolute -inset-1 bg-gradient-to-r from-violet-500/30 to-indigo-500/30 blur-xl rounded-lg"></div>
            <motion.h1 
              initial={{ opacity: 0, y: -20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.2 }}
              className="relative text-3xl sm:text-4xl md:text-5xl font-bold mb-6 tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-violet-400 via-purple-400 to-indigo-500"
            >
              Secure Your Products with BlockThief
            </motion.h1>
          </div>
          
          {/* Glass card */}
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.3 }}
            whileHover={{ y: -5, boxShadow: "0 20px 25px -5px rgba(139, 92, 246, 0.1)" }}
            className="bg-indigo-950/50 backdrop-blur-sm border border-violet-500/20 rounded-xl p-6 mb-8 transition-all duration-300"
          >
            <p className="text-gray-100 text-base sm:text-lg leading-relaxed">
              If you're a certified manufacturer, you can add your product to
              BlockThief and ensure that it's the only one in the world with
              a QR code generated by our advanced blockchain system.
            </p>
            
            <div className="mt-6 flex flex-wrap gap-3">
              {['Tamper-proof', 'Secure', 'Immutable', 'Verifiable'].map((tag, i) => (
                <motion.div 
                  key={i}
                  initial={{ opacity: 0, scale: 0.8 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ duration: 0.3, delay: 0.4 + (i * 0.1) }}
                  whileHover={{ scale: 1.1, backgroundColor: "rgba(139, 92, 246, 0.2)" }}
                  className="bg-indigo-900/60 rounded-full px-3 py-1 text-sm text-violet-400 flex items-center transition-all duration-300"
                >
                  <CheckCircle className="w-3 h-3 mr-1" />
                  {tag}
                </motion.div>
              ))}
            </div>
          </motion.div>
          
          {/* Benefits Grid */}
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.6, delay: 0.5 }}
            className="grid grid-cols-3 gap-3 mb-8"
          >
            {benefits.map((benefit, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.3, delay: 0.6 + (index * 0.1) }}
                whileHover={{ 
                  y: -5, 
                  boxShadow: "0 20px 25px -5px rgba(139, 92, 246, 0.1)",
                  borderColor: "rgba(139, 92, 246, 0.5)"
                }}
                className="bg-indigo-900/30 backdrop-blur-sm rounded-lg p-3 border border-violet-500/10 transition-all duration-300 text-center flex flex-col items-center"
              >
                <div className="bg-gradient-to-r from-violet-600 to-indigo-600 rounded-full p-2 mb-2 text-white">
                  {benefit.icon}
                </div>
                <h4 className="text-violet-300 font-medium text-sm">{benefit.title}</h4>
                <p className="text-gray-400 text-xs mt-1">{benefit.description}</p>
              </motion.div>
            ))}
          </motion.div>
          
          {/* Glowing button */}
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.7 }}
            className="flex justify-center md:justify-start mb-4"
          >
            <div className="relative group">
              <motion.div 
                initial={{ opacity: 0.5 }}
                whileHover={{ opacity: 1 }}
                className="absolute -inset-0.5 bg-gradient-to-r from-violet-500 to-indigo-500 opacity-70 blur-sm rounded-lg transition-opacity duration-300"
              ></motion.div>
              <div className="relative">
                <AddProductButton />
              </div>
            </div>
          </motion.div>
          
          {/* Blockchain certificate */}
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.8 }}
            whileHover={{ 
              y: -5, 
              boxShadow: "0 20px 25px -5px rgba(139, 92, 246, 0.1)",
              borderColor: "rgba(139, 92, 246, 0.5)"
            }}
            className="mt-8 bg-indigo-900/40 backdrop-blur-sm rounded-lg p-4 border border-violet-500/20 flex items-center transition-all duration-300"
          >
            <div className="relative mr-3">
              <motion.div
                animate={{ 
                  scale: [1, 1.2, 1],
                  rotate: [0, 10, 0, -10, 0]
                }}
                transition={{ duration: 5, repeat: Infinity }}
              >
                <Lock className="w-5 h-5 text-violet-400" />
              </motion.div>
              <motion.div
                animate={{ opacity: [0, 0.8, 0] }}
                transition={{ duration: 2, repeat: Infinity }}
                className="absolute -inset-1 bg-violet-400/20 rounded-full blur-sm"
              ></motion.div>
            </div>
            <div>
              <h4 className="text-white font-medium">Blockchain Certified</h4>
              <p className="text-gray-400 text-sm">Every product receives a unique digital signature</p>
            </div>
          </motion.div>
        </motion.div>
      </div>
      
      {/* Add custom animation styles */}
      <style jsx>{`
        .hex-grid {
          background-color: transparent;
          background-image: 
            linear-gradient(to right, rgba(139, 92, 246, 0.05) 1px, transparent 1px),
            linear-gradient(to bottom, rgba(139, 92, 246, 0.05) 1px, transparent 1px);
          background-size: 30px 30px;
          mask-image: radial-gradient(circle, white 60%, transparent 90%);
        }
      `}</style>
    </section>
  );
}

export default ManuSection;