import React from "react";
import ReviewButton from "../buttons/reviewButton";

function reviewSection() {
  return (
    <section className="h-screen grid md:grid">

      <div className="col-span-1 w-full h-full text-center bg-gray-900 py-32 flex items-center justify-center">
        <div className="flex w-full justify-center items-center">
          <div className="flex md:flex-row flex-col items-start justify-between md:p-20 py-12 px-4">
            <div className="flex-1 flex-col md:mr-10">
              <h1 className="text-3xl sm:text-4xl md:text-5xl text-white font-bold mb-6">
                Secure Your Products with Block Thief
              </h1>
              <p className="text-gray-400 text-base sm:text-lg md:text-xl leading-loose mb-8">
                If you're a certified manufacturer, you can add your product to Block Thief and ensure that it's the only one in the world with a QR code generated by a blockchain system.
              </p>

          

              <div className="text-center flex justify-center">

              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

export default reviewSection;
