name: Build and Test Hardhat Project

on:
  push:
    branches:
      - Demo_002

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v2.4.2
        with:
          node-version: '18.12.1'

      - name: Install dependencies
        working-directory: ./contract
        run: yarn

      - name: Build project
        working-directory: ./contract
        run: npx hardhat compile
