name: CI/CD Pipeline

on:
  push:
    branches: [ content-add ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: 'content-add'

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '18.12.1'

    - name: Install dependencies
      working-directory: ./client
      run: npm install

    - name: Build the application
      run: npm run build
