name: Python ML Model

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        cd server/app
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        cd server/app
        pip install flake8
        flake8 app.py
    - name: Test with pytest
      run: |
        cd server/app
        pip install pytest
        pytest
